### PR TITLE
feat: github auth

### PR DESCRIPTION
**Pull request by chikof**
- feat(auth): strategies and services
- chore: badges were removed due to an error
- feat(db): migrations
- feat(auth): github auth

### CODE REVIEW

**Review by yehorovye — COMMENTED** [review]
Why badges were removed?

**Review by yehorovye — CHANGES_REQUESTED** [review]
github oauth types; types may only contain needed information

**Comment by chikof** [comment]
I still need to verify if the oauth is coming from an org or a user

**Review by yehorovye — APPROVED** [review]
seems ready to me, nice job

**Pull request merged**
